// <auto-generated />
using API_Rest_Para_Consulta_de_Datos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Rest_Para_Consulta_de_Datos.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251021033510_BaseV1")]
    partial class BaseV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Rest_Para_Consulta_de_Datos.Modelos.Contribucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreContribucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Contribucion");

                    b.HasKey("Id");

                    b.ToTable("Contribuciones");
                });

            modelBuilder.Entity("API_Rest_Para_Consulta_de_Datos.Modelos.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadMiembros")
                        .HasColumnType("int");

                    b.Property<string>("Colider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoExistencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("API_Rest_Para_Consulta_de_Datos.Modelos.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antiguedad")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contribucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamentos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Miembros");
                });

            modelBuilder.Entity("API_Rest_Para_Consulta_de_Datos.Modelos.Portfolio", b =>
                {
                    b.Property<int>("MiembroID")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentoID")
                        .HasColumnType("int");

                    b.HasKey("MiembroID", "DepartamentoID");

                    b.HasIndex("DepartamentoID");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("ContribucionMiembro", b =>
                {
                    b.Property<int>("ContribucionesId")
                        .HasColumnType("int");

                    b.Property<int>("MiembrosId")
                        .HasColumnType("int");

                    b.HasKey("ContribucionesId", "MiembrosId");

                    b.HasIndex("MiembrosId");

                    b.ToTable("ContribucionMiembro");
                });

            modelBuilder.Entity("API_Rest_Para_Consulta_de_Datos.Modelos.Portfolio", b =>
                {
                    b.HasOne("API_Rest_Para_Consulta_de_Datos.Modelos.Departamento", "Departamento")
                        .WithMany("Portfolios")
                        .HasForeignKey("DepartamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Rest_Para_Consulta_de_Datos.Modelos.Miembro", "Miembro")
                        .WithMany("Portfolios")
                        .HasForeignKey("MiembroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("ContribucionMiembro", b =>
                {
                    b.HasOne("API_Rest_Para_Consulta_de_Datos.Modelos.Contribucion", null)
                        .WithMany()
                        .HasForeignKey("ContribucionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Rest_Para_Consulta_de_Datos.Modelos.Miembro", null)
                        .WithMany()
                        .HasForeignKey("MiembrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Rest_Para_Consulta_de_Datos.Modelos.Departamento", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("API_Rest_Para_Consulta_de_Datos.Modelos.Miembro", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
